services:
  backend:
    container_name: wms-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1323:1323"
    networks:
      - web-network
    volumes:
      - ./backend/public:/app/public:ro
      - ./.env:/app/.env:ro
      - ${JWT_KEY}:/app/wms-jwt.pem:ro
      - ${JWT_PUB_KEY}:/app/wms-jwt-pub.pem:ro
      - ${TLS_CERTIFICATE}:/app/wms-tls.crt:ro
      - ${TLS_KEY}:/app/wms-tls.key:ro
    environment:
      DBUSER: ${DBUSER}
      DBPASS: ${DBPASS}
      DBHOST: ${DBHOST}
      DBPORT: ${DBPORT}
      DBNAME: ${DBNAME}
      JWTKEY: ${JWTKEY}
      JWTPUBKEY: ${JWTPUBKEY}
      TLSCRT: ${TLSCRT}
      TLSKEY: ${TLSKEY}
    develop:
      watch:
        - path: ./backend
          action: rebuild
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:1323/health"]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s

  frontend:
    container_name: wms-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app:cached
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - web-network
    environment:
      VITE_API_URL: ${VITE_API_URL}

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ${TLS_CERTIFICATE}:/etc/nginx/wms-tls.crt:ro
      - ${TLS_KEY}:/etc/nginx/wms-tls.key:ro
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build/client:/usr/share/nginx/html
    depends_on:
      - backend
      - frontend
    ports:
      - "81:80"
      - "444:443"
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
