name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: "Docker Deployment"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSL Certificate
        run: |
          mkdir ./security
          mkdir ./ssl
          echo "$JWT_PUB_KEY" | base64 --decode > ./security/jwtpubkey.pem
          echo "$JWT_KEY" | base64 --decode > ./security/jwtkey.pem
          echo "$SSL_CERTIFICATE" | base64 --decode > ./ssl/certificate.crt
          echo "$SSL_PRIVATE_KEY" | base64 --decode > ./ssl/private.key

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Build Docker Images
        run: docker compose -f compose.yaml build
        env:
          JWT_PUB_KEY: ./security/jwtpubkey.pem
          JWT_KEY: ./security/jwtkey.pem
          SSL_CERTIFICATE: ./ssl/ceritficate.crt
          SSL_PRIVATE_KEY: ./ssl/private.key
          

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy Frontend
        working-directory: frontend
        run: |
          docker build -t knghollow/wms-frontend:dev .
          docker push knghollow/wms-frontend:dev

      - name: Deploy Backend
        working-directory: backend
        run: |
          docker build -t knghollow/wms-backend .
          docker push knghollow/wms-backend
